//
//  TumblrWorker.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 9/12/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TumblrWorker {
  
    func fetchPosts(searchKey: String, completionHandler: @escaping ([TumblrPost]?, Error?) -> Void) {
        Networking.shared.fetchPosts(forSearchKey: searchKey) { (posts, error) in
            guard error == nil else {
                completionHandler(nil, error! as NSError)
                return
            }
            completionHandler(posts, nil)
        }
    }
}
