//
//  TumblrRouter.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 9/12/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TumblrRoutingLogic {
    func routeToShowDetails(displayedPhoto: Tumblr.FetchImages.ViewModel.DisplayedPhoto?)
}

protocol TumblrDataPassing {
    var dataStore: TumblrDataStore? { get }
}

class TumblrRouter: NSObject, TumblrRoutingLogic, TumblrDataPassing {
    weak var viewController: TumblrViewController?
    var dataStore: TumblrDataStore?
  
    // MARK: Routing
  
    func routeToShowDetails(displayedPhoto: Tumblr.FetchImages.ViewModel.DisplayedPhoto?) {
        var destinationVC = TumblrDetailsViewController()
        dataStore?.displayedPhoto = displayedPhoto
        passDataToDetails(source: dataStore!, destination: &destinationVC)
        navigateToDetails(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation
  
    func navigateToDetails(source: TumblrViewController, destination: TumblrDetailsViewController) {
      source.show(destination, sender: nil)
    }
  
    // MARK: Passing data
  
    func passDataToDetails(source: TumblrDataStore, destination: inout TumblrDetailsViewController){
        destination.displayedPhoto = dataStore?.displayedPhoto
    }
}
