//
//  TumblrModels.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 9/12/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import IGListKit

enum Tumblr {
    // MARK: Use cases
  
    enum FetchImages {
        struct Request {
            var text: String
        }
        
        struct Response {
            var posts: [TumblrPost]
            var errorDescription: String?
        }
    
        struct ViewModel {
            class DisplayedPhoto: ListDiffable {
                var url: String
                var originalWidth: Int
                var originalHeight: Int
                var originalImage: UIImage?
                var resizedImage: UIImage?
                var originalImageHash: Int?
                var resizedImageHash: Int?
                
                // MARK: - Init
                
                init(url: String, originalWidth: Int, originalHeight: Int) {
                    self.url = url
                    self.originalWidth = originalWidth
                    self.originalHeight = originalHeight
                }
                
                // MARK: - ListDiffable
                
                func diffIdentifier() -> NSObjectProtocol {
                    return url as NSObjectProtocol
                }
                
                func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
                    guard self !== object else { return true }
                    guard let object = object as? DisplayedPhoto else { return false }
                    return originalWidth == object.originalWidth && originalHeight == object.originalHeight
                }
                
            }
            
            var displayedPhotos: [DisplayedPhoto]
        }
    }
}
