# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'DTARKit-Examples' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IGListKit', '~> 3.0'
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift4.0'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift4.0'
  pod 'SwiftyJSON'
  
end
