//
//  PostsWorker.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 8/25/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PostsWorker {
    
    func fetchPosts(completionHandler: @escaping ([Post]) -> Void) {
        var posts = [Post]()
        
        posts.append(Post(username: "userA",
                          comments: ["Luminous triangle", "Awesome", "Super clean", "Stunning shot"],
                          photoURL: "https://3.bp.blogspot.com/-zcfJuBCjZbQ/Vy1-PgI_XOI/AAAAAAAAAes/OTf1ItdGaX0kPk5AlQKZb6dySSCJY1QzQCKgB/s1600/blaring%2Bsmoke.jpg"))
        posts.append(Post(username: "userB",
                          comments: ["he simplicity here is superb", "thanks!", "That's always so kind of you!", "I think you might like this"],
                          photoURL: "https://media-cdn.tripadvisor.com/media/photo-s/01/90/78/c5/sunset-over-dinner-nice.jpg"))
        posts.append(Post(username: "userC",
                          comments: ["So good"],
                          photoURL: "http://www.telegraph.co.uk/content/dam/Travel/leadAssets/22/75/Promenade-des-Angl_2275260a-xlarge.jpg"))
        posts.append(Post(username: "userD",
                          comments: ["hope she might like it.", "I love it."],
                          photoURL: "http://www.cheapflightslab.com/wp-content/uploads/2017/01/nice.1466255.142.jpg"))
        
        completionHandler(posts)
    }
}

