//
//  PostsInteractor.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 8/25/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostsBusinessLogic {
    func fetchPosts(request: Posts.FetchPosts.Request)
}

protocol PostsDataStore {
    var posts: [Post]? { get }
}

class PostsInteractor: PostsBusinessLogic, PostsDataStore {
    var presenter: PostsPresentationLogic?
    var worker: PostsWorker?
    var posts: [Post]?
  
    // MARK: Fetch Posts
  
  func fetchPosts(request: Posts.FetchPosts.Request) {
    worker = PostsWorker()
    
    worker?.fetchPosts(completionHandler: { (posts) in
        self.posts = posts
        let response = Posts.FetchPosts.Response(posts: posts)
        self.presenter?.presentFetchedPosts(response: response)
    })
  }
}
