//
//  ListExamplesInteractor.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 8/25/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListExamplesBusinessLogic {
    func fetchExamples(request: ListExamples.FetchExamples.Request)
}

protocol ListExamplesDataStore {
    var examples: [Example]? { get }
}

class ListExamplesInteractor: ListExamplesBusinessLogic, ListExamplesDataStore {

    var presenter: ListExamplesPresentationLogic?
    var worker = ListExamplesWorker()
    
    var examples: [Example]?
    
  
    // MARK: - Fetch examples
    
    func fetchExamples(request: ListExamples.FetchExamples.Request) {
        worker.fetchExamples { (examples) in
            self.examples = examples
            let response = ListExamples.FetchExamples.Response(examples: examples)
            self.presenter?.presentFetchedOrders(response: response)
        }
    }
}
