//
//  ListExamplesModels.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 8/25/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import IGListKit

enum ListExamples {
  // MARK: Use cases
  
  enum FetchExamples {
    
    struct Request {
    }
    
    struct Response {
        var examples: [Example]
    }
    
    struct ViewModel {
        struct DisplayedExample: Diffable {
            var id: Int
            var name: String
            
            var diffIdentifier: String {
                return String(id)
            }
            
            static func ==(lhs: DisplayedExample, rhs: DisplayedExample) -> Bool {
                return lhs.name == rhs.name
            }
        }
        var displayedExamples: [DisplayedExample]
    }
    
  }
}


