//
//  ListExamplesRouter.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 8/25/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListExamplesRoutingLogic {
    func routeToShowPosts()
}

protocol ListExamplesDataPassing {
    var dataStore: ListExamplesDataStore? { get }
}

class ListExamplesRouter: NSObject, ListExamplesRoutingLogic, ListExamplesDataPassing {
    
    weak var viewController: ListExamplesViewController?
    var dataStore: ListExamplesDataStore?
  
    // MARK: Routing
  
    func routeToShowPosts() {
        var destinationVC = PostsViewController()
        passDataToPosts(source: dataStore!, destination: &destinationVC)
        navigateToPosts(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation
  
    func navigateToPosts(source: ListExamplesViewController, destination: PostsViewController){
        source.show(destination, sender: nil)
    }
  
    // MARK: Passing data
  
    func passDataToPosts(source: ListExamplesDataStore, destination: inout PostsViewController) {
        
    }
}
