//
//  TumblrDetailsModels.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 9/15/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TumblrDetails {
    // MARK: Use cases
  
    enum Something {
        struct Request {
        }
        
        struct Response {
        }
    
        struct ViewModel {
        }
    }
}
