//
//  TumblrDetailsViewController.swift
//  DTARKit-Examples
//
//  Created by Dima Tsurkan on 9/15/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TumblrDetailsDisplayLogic: class {
    func displaySomething(viewModel: TumblrDetails.Something.ViewModel)
}

class TumblrDetailsViewController: UIViewController, TumblrDetailsDisplayLogic {
    var interactor: TumblrDetailsBusinessLogic?
    var router: (NSObjectProtocol & TumblrDetailsRoutingLogic & TumblrDetailsDataPassing)?
    var displayedPhoto: Tumblr.FetchImages.ViewModel.DisplayedPhoto?
    
    fileprivate let imageView: UIImageView = {
        let view = UIImageView()
        view.contentMode = .scaleAspectFill
        view.clipsToBounds = true
        view.backgroundColor = UIColor(white: 0.95, alpha: 1)
        return view
    }()

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = TumblrDetailsInteractor()
        let presenter = TumblrDetailsPresenter()
        let router = TumblrDetailsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
        configureView()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        imageView.frame = self.view.bounds
        imageView.contentMode = .scaleAspectFit
    }
    
    // MARK: - Internal
    private func configureView() {
        view.addSubview(imageView)
        imageView.image = displayedPhoto?.originalImage
        configureNavigationBar()
    }
    
    func configureNavigationBar() {
        navigationItem.title = "Details"
    }
  
    // MARK: Do something
  
    func doSomething() {
        let request = TumblrDetails.Something.Request()
        interactor?.doSomething(request: request)
    }
  
    func displaySomething(viewModel: TumblrDetails.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
